language: node_js
node_js:
- '8'
dist: trusty
services:
- mongodb
env:
- CI=false NODE_ENV=ci PORT=3000
cache:
  directories:
  - node_modules
  - client/node_modules
install:
- npm install
- npm run build
script:
- nohup npm run start &
- sleep 3
- npm run test
notifications:
  email:
    recipients:
    - moogunjung@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: Oz5gkGKt2v4plnb91MmbrCfJf4Om/rZtKf2LbML7nRcxo4JSLN1c3Wu3Ne8ywFXMTOHrp84RIvURhAGzWoeuhBzHk5Chx+7E8GzwZ8GSFe0AI33YAqigrzWFnwcv9DKJjJlD3+JPD3/3I1VGiJVB+aWSolSL+k+3c2UPBNw6yx6D5crTDLb7ZUc1xXkx9PZmVF/Hl5SjA0u+Q8pEoiduwMrAZ4GwdaYW6XSEbQgikSwZ/MwLd2/RZhGqR/5gm3fZAuCCnX7Wes38gtPPpLOgMI+7WZS15R1XYZz0qHPnekpsL2M3vJus/j6yx/kCg5c1XpnpjxBSji9YWV3S28Ahls8Tjqy8Z8UIrg/4ZQZvkZUKQ9WJFlllFCj2BN1M45s2Y9hxr5DVmhEMeohCwfewOvIwhkz46yQSybE2ZeTtOhSGIa4NAFDx9N5Tj4hr8s/QUkzjmQI7Y9lF/id/p7yf6norEuTbVHpbpvov26tray9JNnGYIidO7bzES40f1nKohhBWfXDmI2UEAjRxi+oBqFCoHNj9gIVFstJUIwVTm9EZfVBeJ0pjqkiphnAHY/yz4NrIPseqjaIaW0+ueuAbTK35mfAVbeZy9XAsDesonOLIocGQL88zmsSoPtXSYko8P8mi5qtZguPXDvnMUGWktdhjJwocL5u++gW3NjehEk4=
  app: node-react-dev
  on:
    repo: Moogun/Email-Survey
